### PR TITLE
feat: Pod disruption budget

### LINKED ISSUE #323: Helm chart should provide a PDB
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/bank-vaults/vault-operator/issues) for an issue that matches the one I want to file, without success.
- [X] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct/).

### Problem Description

Helm charts support for HA of operator could be better

### Proposed Solution

Helm chart should provide a podDisruptionBudget in case there replicaCount is > 1. 
Also some pod Antiaffinity or topologySPreadConstraints could be usefull in order to make operator HA. 

### Alternatives Considered

Implement own PDB 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by camaeel**
## Overview

Implement pod disruption budget for vault-operator helm-chart

Fixes #323

### CODE REVIEW

**Review by akijakya — DISMISSED** [review]
Hi @camaeel, thanks for your contribution! Could you take a look at the linting error?

**Comment by camaeel** [comment]
@akijakya should be fixed now

**Comment by akijakya** [comment]
Please also run `make gen-helm-docs`, so the new values are included in the chart readme, thanks!

**Comment by ramizpolic** [comment]
> Please also run `make gen-helm-docs`, so the new values are included in the chart readme, thanks!

Hi @camaeel, could you please resolve this so we can merge it? Thanks!

**Comment by camaeel** [comment]
Done

**Review by ramizpolic — APPROVED** [review]
Thanks for the submission @camaeel!

**Pull request merged**
