### PR TITLE
ci: add magic nix cache

### LINKED ISSUE #105: Add caching or remove nix from pipeline build steps
Configuring the NIX environment takes 3 minutes for every pipeline step, making it one of the longest pipeline steps. Using Makefile should be comparably faster + configuring other setup steps (e.g. configuring Go) can be fully cached between runs. If it is possible to add cache to nix, then it is worth considering as well.

### PR DESCRIPTION
**Pull request by sagikazarmark**
## Overview

Fixes #105

### CODE REVIEW

**Comment by ramizpolic** [comment]
I don't see much difference in pipeline steps with and without caching, is this maybe because this was the first execution or perhaps that it's not present on main branch, @sagikazarmark ?

**Comment by sagikazarmark** [comment]
Main branch (without caching): https://github.com/bank-vaults/vault-operator/actions/workflows/ci.yaml?query=branch%3Amain

Cache branch: https://github.com/bank-vaults/vault-operator/actions/workflows/ci.yaml?query=branch%3Anix-cache

Test job without caching: ~7 minutes
Test job with Nix caching only: ~3 minutes
Test job with Nix+Go caching only: pending

**Review by ramizpolic — APPROVED** [review]
Great improvements 🚀

**Review by akijakya — DISMISSED** [review]
🥳

**Comment by sagikazarmark** [comment]
Managed to improve things further by segmenting the Go cache for each job. It takes up more space in the cache, but different jobs download different dependencies (eg. build doesn't download test dependencies, etc)

**Pull request merged**
