### PR TITLE
Upgrade Kubernetes API to 1.27

### PR DESCRIPTION
**Pull request by ramizpolic**
## Overview

Tracks #47

## Notes for reviewer
* `controller-runtime` interfaces have slightly changed, the new changes take those into account

### CODE REVIEW

**Comment by ramizpolic** [comment]
Maybe we could also bump CI acceptance test Kube version against v1.27.2

**Comment by akijakya** [comment]
> Maybe we could also bump CI acceptance test Kube version against v1.27.2

Here 😉 https://github.com/bank-vaults/vault-operator/pull/83

**Comment by sagikazarmark** [comment]
These are breaking change, right?

>     * `vaultv1alpha1.Vault.Spec.PodAntiAffinity` has been replaced with `vaultv1alpha1.Vault.Spec.Affinity.PodAntiAffinity`
> 
>     * `vaultv1alpha1.Vault.Spec.PodAffinity` has been replaced with `vaultv1alpha1.Vault.Spec.Affinity.PodAffinity`

Do we need a webhook and a new API version to support backward compatibility (ie. if someone updates the operator to a version with this change, it shouldn't break existing instances)?

**Comment by sagikazarmark** [comment]
> Merge branch 'main' into feature/k8s.io-v0.27.2

Please rebase instead of merging main.

**Pull request merged**
